"""Offline label generation and supervised training for the ANN+GSBF baseline's
ANN stage (Fathy et al., 2021) — see baselines/ann_gsbf.py.

The ANN predicts the near-optimal active-RRH count from demand/channel
summary features; ground-truth labels are generated by exhaustively scoring
every candidate active-RRH count (1..R) on synthetic (channel, demand)
scenarios, reusing CRANEnv's own tested SINR/power-model physics rather than
reimplementing it, so the labels are consistent with the live environment.
"""

import argparse
from pathlib import Path
from typing import Any, Dict, Tuple

import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import yaml  # type: ignore[import-untyped]

from baselines.ann_gsbf import ANNPredictor, DEFAULT_CHECKPOINT_PATH, extract_features
from cran_env import CRANEnv


def _score_candidate(
    env: CRANEnv,
    channel_gains: np.ndarray,
    demands_bps: np.ndarray,
    rrh_scores: np.ndarray,
    req_active: int,
) -> float:
    """Score one candidate active-RRH count on a fixed (channel, demand) scenario.

    Reuses CRANEnv's own SINR/serving-RRH physics (`_signal_interference`) and
    power model (`PowerModel.compute_rrh_power`/`compute_fronthaul_power`)
    directly on a snapshotted channel/demand pair, rather than calling the
    stateful `step()` (which would advance the environment's hour/channel).
    BBU and switching costs are omitted from this one-shot scoring — they
    depend on prior state (switching) or a BBU-load assumption not relevant
    to a single-scenario RRH-count decision — so this is a simplification of
    the full reward, not a full training-time reward computation.
    """
    active_indices = np.argsort(rrh_scores)[::-1][:req_active]
    rrh_on = np.zeros(env.n_rrh, dtype=bool)
    rrh_on[active_indices] = True

    total_demand_mbps = float(np.sum(demands_bps)) / 1e6
    power = np.zeros(env.n_rrh, dtype=np.float32)
    power[active_indices] = np.clip(
        (total_demand_mbps / (req_active * 50.0)) * env.p_max_w,
        0.1 * env.p_max_w,
        env.p_max_w,
    )

    bandwidth_share = np.zeros(env.n_rrh, dtype=np.float32)
    bandwidth_share[active_indices] = 1.0 / req_active

    original_channel_gains = env.channel_gains
    env.channel_gains = channel_gains
    try:
        signal, interference, serving_rrh = env._signal_interference(rrh_on, power)
    finally:
        env.channel_gains = original_channel_gains

    sinr = np.where(signal > 0.0, signal / (interference + env.noise_power_w), 0.0)
    served = serving_rrh >= 0
    bw_hz = np.zeros_like(sinr)
    bw_hz[served] = bandwidth_share[serving_rrh[served]] * env.channel.bandwidth
    capacity_bps = bw_hz * np.log2(1.0 + sinr)
    qos_violations_bps = np.maximum(0.0, demands_bps - capacity_bps)
    throughput_mbps = np.sum(capacity_bps) / 1e6

    p_total = env.power.compute_rrh_power(
        rrh_on, power
    ) + env.power.compute_fronthaul_power(rrh_on)
    ee_mbit_per_joule = throughput_mbps / (p_total + 1e-6)
    qos_penalty = env.beta_qos * (np.sum(qos_violations_bps) / 1e6)
    return float(env.alpha_energy * ee_mbit_per_joule - qos_penalty)


def generate_labelled_dataset(
    config_path: str, n_samples: int = 200, seed: int = 0
) -> Tuple[np.ndarray, np.ndarray]:
    """Generate (feature, label) pairs by exhaustively scoring every
    candidate active-RRH count on synthetic scenarios sampled from the
    environment's own channel/traffic models.

    Returns:
        Tuple[np.ndarray, np.ndarray]: (features (n_samples, 8), labels
            (n_samples,) — the best-scoring active-RRH count as a fraction
            of n_rrh, in (0, 1]).
    """
    with open(config_path, "r") as f:
        cfg = yaml.safe_load(f)
    env = CRANEnv(cfg)
    rng = np.random.default_rng(seed)

    features = []
    labels = []
    for _ in range(n_samples):
        env.reset(seed=int(rng.integers(0, 2**31 - 1)))
        channel_gains = env.channel_gains.copy()
        # Reuse the exact demand realization reset() already sampled and
        # embedded in the environment's state, rather than independently
        # resampling here -- otherwise this scenario's scored demand would
        # not match the one env.current_demands_bps (and any subsequent
        # env.step()) actually uses (cran_env/cran_env.py's fixed
        # single-sample-per-hour behavior).
        demands_bps = env.current_demands_bps.copy()
        gains_mag = np.abs(channel_gains)
        rrh_scores = np.mean(gains_mag, axis=1)

        best_score = -np.inf
        best_req_active = 1
        for req_active in range(1, env.n_rrh + 1):
            score = _score_candidate(
                env, channel_gains, demands_bps, rrh_scores, req_active
            )
            if score > best_score:
                best_score = score
                best_req_active = req_active

        demands_mbps = demands_bps / 1e6
        features.append(
            extract_features(
                gains_mag,
                demands_mbps,
                env.n_rrh,
                env.p_max_w,
                env.noise_power_w,
                env.channel.bandwidth,
            )
        )
        labels.append(best_req_active / env.n_rrh)

    return np.array(features, dtype=np.float32), np.array(labels, dtype=np.float32)


def train_ann_predictor(
    config_path: str = "config/small_network.yaml",
    n_samples: int = 200,
    epochs: int = 200,
    lr: float = 1e-3,
    seed: int = 0,
    save_path: str = str(DEFAULT_CHECKPOINT_PATH),
) -> Dict[str, Any]:
    """Generate a labelled dataset and train the ANN+GSBF baseline's predictor.

    Features are standardized (zero mean, unit variance, per dimension)
    before training -- the raw features span roughly six orders of
    magnitude (e.g. demand-derived features ~O(10-100) vs. channel-gain
    magnitudes ~O(1e-5)), which otherwise starves the smaller-scale
    features of gradient signal. The per-feature mean/std used are saved
    alongside the model weights so inference (baselines/ann_gsbf.py)
    applies the identical transform.
    """
    features, labels = generate_labelled_dataset(
        config_path, n_samples=n_samples, seed=seed
    )
    feat_mean = features.mean(axis=0)
    feat_std = features.std(axis=0)
    feat_std[feat_std < 1e-8] = 1.0  # guard against zero-variance features (e.g. n_rrh)
    features_norm = (features - feat_mean) / feat_std

    x = torch.FloatTensor(features_norm)
    y = torch.FloatTensor(labels).unsqueeze(1)

    model = ANNPredictor()
    opt = optim.Adam(model.parameters(), lr=lr, weight_decay=1e-3)
    loss_fn = nn.MSELoss()

    losses = []
    for _ in range(epochs):
        opt.zero_grad()
        pred = model(x)
        loss = loss_fn(pred, y)
        loss.backward()
        opt.step()
        losses.append(float(loss.item()))

    if save_path is not None:
        out_path = Path(save_path)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        torch.save(
            {
                "model_state": model.state_dict(),
                # Stored as tensors, not numpy arrays: PyTorch 2.6+'s
                # torch.load defaults to weights_only=True, whose safe
                # unpickler allows tensors but rejects numpy arrays.
                "feat_mean": torch.from_numpy(feat_mean),
                "feat_std": torch.from_numpy(feat_std),
            },
            out_path,
        )
        print(f"Saved trained ANN+GSBF predictor to {out_path}")

    return {
        "final_loss": losses[-1],
        "losses": losses,
        "n_samples": n_samples,
    }


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Train the ANN+GSBF baseline's active-RRH-count predictor"
    )
    parser.add_argument(
        "--config",
        type=str,
        default="config/small_network.yaml",
        help="Config file path",
    )
    parser.add_argument(
        "--n-samples",
        type=int,
        default=200,
        help="Number of synthetic training scenarios",
    )
    parser.add_argument("--epochs", type=int, default=200, help="Training epochs")
    parser.add_argument("--lr", type=float, default=1e-3, help="Adam learning rate")
    parser.add_argument("--seed", type=int, default=0, help="Random seed")
    parser.add_argument(
        "--save-path",
        type=str,
        default=str(DEFAULT_CHECKPOINT_PATH),
        help="Where to save the trained checkpoint",
    )
    args = parser.parse_args()

    result = train_ann_predictor(
        config_path=args.config,
        n_samples=args.n_samples,
        epochs=args.epochs,
        lr=args.lr,
        seed=args.seed,
        save_path=args.save_path,
    )
    print(f"Trained ANN+GSBF predictor: final MSE loss = {result['final_loss']:.4f}")
